<a href="https://colab.research.google.com/github/avi78/AI_ML/blob/main/Program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import heapq
grmap = { # 1st graph
 'A': {'B': 3, 'C': 5},
 'B': {'A': 3, 'C': 2, 'D': 8},
 'C': {'A': 5, 'B': 2, 'D': 1, 'E': 4},
 'D': {'B': 8, 'C': 1, 'E': 6},
 'E': {'C': 4, 'D': 6}
}
heuristic = {
 'A': 8,
 'B': 6,
 'C': 4,
 'D': 3,
 'E': 0
}
def a_star(grmap,heuristic,start,goal):
  open_list = [(0,start)]
  closed_set = set()
  g_score = {location:float('inf') for location in grmap}
  g_score[start] = 0
  while open_list:
    current_g,current_node = heapq.heappop(open_list)
    if current_node == goal:
      return g_score[goal]
    if current_node in closed_set:
      continue
    closed_set.add(current_node)
    for neighbour,distance in grmap[current_node].items():
      tentative_g = g_score[current_node] + distance
      if tentative_g < g_score[neighbour]:
        g_score[neighbour]=tentative_g
        f_score = tentative_g + heuristic[neighbour]
        heapq.heappush(open_list,(f_score,neighbour))
  return float('inf')
start = 'A'
goal = 'E'
shortest_distance = a_star(grmap,heuristic,start,goal)
if shortest_distance<float('inf'):
  print(f"Shortest distance from {start} to {goal} is {shortest_distance} km")
else:
  print(f"No path found from {start} to {goal}")


Shortest distance from A to E is 9 km


In [4]:
import random
import numpy as np
import time
z=0
choice=[0,1]
n = int(input("Enter room size: "))
room = np.empty((n,n))
for x in range(n):
  for y in range(n):
    room[x][y] = random.choice(choice)
print("Room Before\n",room)
start = time.time()
for x in range(n):
  for y in range(n):
    if (room[x][y]==1):
      room[x][y] = 0
      print(f"cleaned {x} {y}")
      z+=1
    else:
      pass
end = time.time()
per = (z/(n*n))*100
print("Room after\n",room)
print("No. of room cleaned",z)
print("Time: ",(end-start))
print("Performance: ",per)

Enter room size: 4
Room Before
 [[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 1. 1.]
 [1. 0. 0. 0.]]
cleaned 0 2
cleaned 1 1
cleaned 2 1
cleaned 2 2
cleaned 2 3
cleaned 3 0
Room after
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
No. of room cleaned 6
Time:  0.0016260147094726562
Performance:  37.5


In [7]:
maximum, minimum = 1000, -1000
def fun_alphabeta(d,node,maxp,v,A,B):
    if d == 3:
        return v[node]
    if maxp:
        best = minimum
        for i in range(0,2):
            value = fun_alphabeta(d+1,node*2+i,False,v,A,B)
            best = max(best,value)
            A = max(A,best)
            if B<=A:
                break
        return best
    else:
        best = maximum
        for i in range(0,2):
            value = fun_alphabeta(d+1,node*2+i,True,v,A,B)
            best = min(best,value)
            B = min(B,best)
            if B<=A:
                break
        return best
scr = []
x = int(input("Enter total number of leaf node: "))
for i in range(x):
    y = int(input("Enter node value "))
    scr.append(y)
d = int(input("Enter depth value: "))
node = int(input("Enter node value: "))
print("The optimal value is: ",fun_alphabeta(d,node,True,scr,minimum,maximum))


Enter total number of leaf node: 8
Enter node value 2
Enter node value 3
Enter node value 5
Enter node value 9
Enter node value 0
Enter node value 1
Enter node value 7
Enter node value 5
Enter depth value: 0
Enter node value: 0
The optimal value is:  3


In [9]:
board = [" " for i in range(9)]
def print_board():
  row1 = f"|{board[0]}|{board[1]}|{board[2]}|"
  row2 = f"|{board[3]}|{board[4]}|{board[5]}|"
  row3 = f"|{board[6]}|{board[7]}|{board[8]}|"
  print()
  print(row1)
  print(row2)
  print(row3)
  print()

def player_move(icon):
  if icon == "X":
    number = 1
  elif icon == "O":
    number = 2
  print(f"Your Turn player {number}")
  choice = int(input("enter your move(1-9): ").strip())
  if board[choice-1] == " ":
    board[choice-1] = icon
  else:
    print()
    print("That space is already taken")

def is_victory(icon):
  if (board[0] == icon and board[1] == icon and board[2] == icon) or (board[3] == icon and board[4] == icon and board[5] == icon) or (board[6]==icon and board[7]==icon and board[8]==icon) or (board[0] == icon and board[3] == icon and board[6] == icon) or (board[1] == icon and board[4] == icon and board[7] == icon) or (board[2] == icon and board[5] == icon and board[8] == icon) or (board[0] == icon and board[4] == icon and board[8] == icon) or (board[2] == icon and board[4] == icon and board[6] == icon):
    return True
  else:
    return False
def is_draw():
  if " " not in board:
    return True
  else:
    return False
while True:
  print_board()
  player_move('X')
  print_board()
  if is_victory("X"):
    print("X wins! Congratulations!")
    break
  elif is_draw():
    print("It's a draw!")
    break
  player_move("O")
  if is_victory("O"):
    print_board()
    print("O wins! Congratulations!")
    break
  elif is_draw():
    print("It's a draw")
    break


| | | |
| | | |
| | | |

Your Turn player 1
enter your move(1-9): 1

|X| | |
| | | |
| | | |

Your Turn player 2
enter your move(1-9): 2

|X|O| |
| | | |
| | | |

Your Turn player 1
enter your move(1-9): 4

|X|O| |
|X| | |
| | | |

Your Turn player 2
enter your move(1-9): 6

|X|O| |
|X| |O|
| | | |

Your Turn player 1
enter your move(1-9): 7

|X|O| |
|X| |O|
|X| | |

X wins! Congratulations!


In [15]:
def mcculloch_pitts(inputs,weights,threshold):
  assert len(inputs) == len(weights), "Number of inputs must match number of weights"
  weighted_sum = sum(x*w for x,w in zip(inputs,weights))
  output = 1 if weighted_sum >= threshold else 0
  return output
def test_logic(gate):
  print(f"Testing {gate} gate:")
  if gate == "AND":
    inputs = [(0,0),(0,1),(1,0),(1,1)]
    weights = (1,1)
    threshold = 2
  elif gate == "OR":
    inputs = [(0,0),(0,1),(1,0),(1,1)]
    weights = (1,1)
    threshold = 1
  elif gate == "XOR":
    inputs = [(0,0),(0,1),(1,0),(1,1)]
    weights_and = (1,-1)
    weights_andnot = (-1,1)
    weights_or = (1,1)
    threshold = 1
    for input_pair in inputs:
      input1,input2 = input_pair
      and_result = mcculloch_pitts(input_pair,weights_and,threshold)
      andnot_result = mcculloch_pitts(input_pair,weights_andnot,threshold)
      or_result = mcculloch_pitts((and_result,andnot_result),weights_or,threshold)
      print(f"{input_pair}:{or_result}")
    return
  elif gate == "AND NOT":
    inputs = [(0,0),(0,1),(1,0),(1,1)]
    weights = (1,-1)
    threshold = 1
  else:
    print("Invalid logic gate")
  for input_pair in inputs:
    result = mcculloch_pitts(input_pair,weights,threshold)
    print(f"{input_pair}:{result}")

test_logic("AND")
test_logic("OR")
test_logic("XOR")
test_logic("AND NOT")

Testing AND gate:
(0, 0):0
(0, 1):0
(1, 0):0
(1, 1):1
Testing OR gate:
(0, 0):0
(0, 1):1
(1, 0):1
(1, 1):1
Testing XOR gate:
(0, 0):0
(0, 1):1
(1, 0):1
(1, 1):0
Testing AND NOT gate:
(0, 0):0
(0, 1):0
(1, 0):1
(1, 1):0


In [18]:
import numpy as np
theta = 1
epoch = 3
class Perceptron(object):
  def __init__(self,input_size,learning_rate = 0.2):
    self.learning_rate = learning_rate
    self.weights = np.zeros(input_size + 1)
  def predict(self,x):
    return (np.dot(x,self.weights[1:]) + self.weights[0])
  def train(self,x,y,weights):
    for inputs,label in zip(x,y):
      net_in = self.predict(inputs)
      if net_in > theta:
        y_out = 1
      elif net_in < -theta:
        y_out = -1
      else:
        y_out = 0
      if y_out != label:
        self.weights[1:] += self.learning_rate*label*inputs
        self.weights[0] += self.learning_rate*label
      print(inputs,net_in,label,y_out,self.weights)
if __name__ == "__main__":
  x = []
  x.append(np.array([1,1]))
  x.append(np.array([1,-1]))
  x.append(np.array([-1,1]))
  x.append(np.array([-1,-1]))
  y = np.array([1,-1,-1,-1])
perceptron = Perceptron(2)
for i in range(epoch):
  print("Epoch",i)
  print("X1 X2","Net","T","Y","B Weights")
  weights = perceptron.weights
  print("Initial Weights",weights)
  perceptron.train(x,y,weights)

Epoch 0
X1 X2 Net T Y B Weights
Initial Weights [0. 0. 0.]
[1 1] 0.0 1 0 [0.2 0.2 0.2]
[ 1 -1] 0.2 -1 0 [0.  0.  0.4]
[-1  1] 0.4 -1 0 [-0.2  0.2  0.2]
[-1 -1] -0.6000000000000001 -1 0 [-0.4  0.4  0.4]
Epoch 1
X1 X2 Net T Y B Weights
Initial Weights [-0.4  0.4  0.4]
[1 1] 0.4 1 0 [-0.2  0.6  0.6]
[ 1 -1] -0.2 -1 0 [-0.4  0.4  0.8]
[-1  1] -5.551115123125783e-17 -1 0 [-0.6  0.6  0.6]
[-1 -1] -1.8000000000000003 -1 -1 [-0.6  0.6  0.6]
Epoch 2
X1 X2 Net T Y B Weights
Initial Weights [-0.6  0.6  0.6]
[1 1] 0.6000000000000001 1 0 [-0.4  0.8  0.8]
[ 1 -1] -0.4000000000000001 -1 0 [-0.6  0.6  1. ]
[-1  1] -0.20000000000000018 -1 0 [-0.8  0.8  0.8]
[-1 -1] -2.4000000000000004 -1 -1 [-0.8  0.8  0.8]
